/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVersamentoRouteImport } from './routes/_app.versamento'
import { Route as AppStoricoRouteImport } from './routes/_app.storico'
import { Route as AppStampeRouteImport } from './routes/_app.stampe'
import { Route as AppSpedizioniRouteImport } from './routes/_app.spedizioni'
import { Route as AppRicettarioRouteImport } from './routes/_app.ricettario'
import { Route as AppMagazzinoRouteImport } from './routes/_app.magazzino'
import { Route as AppDiagnosticaRouteImport } from './routes/_app.diagnostica'
import { Route as AppAnagraficaRouteImport } from './routes/_app.anagrafica'
import { Route as AppDiagnosticaIndexRouteImport } from './routes/_app.diagnostica.index'
import { Route as AppDiagnosticaLogRouteImport } from './routes/_app.diagnostica.log'
import { Route as AppDiagnosticaErroriRouteImport } from './routes/_app.diagnostica.errori'
import { Route as AppDiagnosticaCodiciErroriRouteImport } from './routes/_app.diagnostica.codici-errori'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVersamentoRoute = AppVersamentoRouteImport.update({
  id: '/versamento',
  path: '/versamento',
  getParentRoute: () => AppRoute,
} as any)
const AppStoricoRoute = AppStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AppRoute,
} as any)
const AppStampeRoute = AppStampeRouteImport.update({
  id: '/stampe',
  path: '/stampe',
  getParentRoute: () => AppRoute,
} as any)
const AppSpedizioniRoute = AppSpedizioniRouteImport.update({
  id: '/spedizioni',
  path: '/spedizioni',
  getParentRoute: () => AppRoute,
} as any)
const AppRicettarioRoute = AppRicettarioRouteImport.update({
  id: '/ricettario',
  path: '/ricettario',
  getParentRoute: () => AppRoute,
} as any)
const AppMagazzinoRoute = AppMagazzinoRouteImport.update({
  id: '/magazzino',
  path: '/magazzino',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticaRoute = AppDiagnosticaRouteImport.update({
  id: '/diagnostica',
  path: '/diagnostica',
  getParentRoute: () => AppRoute,
} as any)
const AppAnagraficaRoute = AppAnagraficaRouteImport.update({
  id: '/anagrafica',
  path: '/anagrafica',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticaIndexRoute = AppDiagnosticaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDiagnosticaRoute,
} as any)
const AppDiagnosticaLogRoute = AppDiagnosticaLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppDiagnosticaRoute,
} as any)
const AppDiagnosticaErroriRoute = AppDiagnosticaErroriRouteImport.update({
  id: '/errori',
  path: '/errori',
  getParentRoute: () => AppDiagnosticaRoute,
} as any)
const AppDiagnosticaCodiciErroriRoute =
  AppDiagnosticaCodiciErroriRouteImport.update({
    id: '/codici-errori',
    path: '/codici-errori',
    getParentRoute: () => AppDiagnosticaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/anagrafica': typeof AppAnagraficaRoute
  '/diagnostica': typeof AppDiagnosticaRouteWithChildren
  '/magazzino': typeof AppMagazzinoRoute
  '/ricettario': typeof AppRicettarioRoute
  '/spedizioni': typeof AppSpedizioniRoute
  '/stampe': typeof AppStampeRoute
  '/storico': typeof AppStoricoRoute
  '/versamento': typeof AppVersamentoRoute
  '/diagnostica/codici-errori': typeof AppDiagnosticaCodiciErroriRoute
  '/diagnostica/errori': typeof AppDiagnosticaErroriRoute
  '/diagnostica/log': typeof AppDiagnosticaLogRoute
  '/diagnostica/': typeof AppDiagnosticaIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/anagrafica': typeof AppAnagraficaRoute
  '/magazzino': typeof AppMagazzinoRoute
  '/ricettario': typeof AppRicettarioRoute
  '/spedizioni': typeof AppSpedizioniRoute
  '/stampe': typeof AppStampeRoute
  '/storico': typeof AppStoricoRoute
  '/versamento': typeof AppVersamentoRoute
  '/': typeof AppIndexRoute
  '/diagnostica/codici-errori': typeof AppDiagnosticaCodiciErroriRoute
  '/diagnostica/errori': typeof AppDiagnosticaErroriRoute
  '/diagnostica/log': typeof AppDiagnosticaLogRoute
  '/diagnostica': typeof AppDiagnosticaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/anagrafica': typeof AppAnagraficaRoute
  '/_app/diagnostica': typeof AppDiagnosticaRouteWithChildren
  '/_app/magazzino': typeof AppMagazzinoRoute
  '/_app/ricettario': typeof AppRicettarioRoute
  '/_app/spedizioni': typeof AppSpedizioniRoute
  '/_app/stampe': typeof AppStampeRoute
  '/_app/storico': typeof AppStoricoRoute
  '/_app/versamento': typeof AppVersamentoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/diagnostica/codici-errori': typeof AppDiagnosticaCodiciErroriRoute
  '/_app/diagnostica/errori': typeof AppDiagnosticaErroriRoute
  '/_app/diagnostica/log': typeof AppDiagnosticaLogRoute
  '/_app/diagnostica/': typeof AppDiagnosticaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/anagrafica'
    | '/diagnostica'
    | '/magazzino'
    | '/ricettario'
    | '/spedizioni'
    | '/stampe'
    | '/storico'
    | '/versamento'
    | '/diagnostica/codici-errori'
    | '/diagnostica/errori'
    | '/diagnostica/log'
    | '/diagnostica/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/anagrafica'
    | '/magazzino'
    | '/ricettario'
    | '/spedizioni'
    | '/stampe'
    | '/storico'
    | '/versamento'
    | '/'
    | '/diagnostica/codici-errori'
    | '/diagnostica/errori'
    | '/diagnostica/log'
    | '/diagnostica'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/anagrafica'
    | '/_app/diagnostica'
    | '/_app/magazzino'
    | '/_app/ricettario'
    | '/_app/spedizioni'
    | '/_app/stampe'
    | '/_app/storico'
    | '/_app/versamento'
    | '/_app/'
    | '/_app/diagnostica/codici-errori'
    | '/_app/diagnostica/errori'
    | '/_app/diagnostica/log'
    | '/_app/diagnostica/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/versamento': {
      id: '/_app/versamento'
      path: '/versamento'
      fullPath: '/versamento'
      preLoaderRoute: typeof AppVersamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storico': {
      id: '/_app/storico'
      path: '/storico'
      fullPath: '/storico'
      preLoaderRoute: typeof AppStoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stampe': {
      id: '/_app/stampe'
      path: '/stampe'
      fullPath: '/stampe'
      preLoaderRoute: typeof AppStampeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spedizioni': {
      id: '/_app/spedizioni'
      path: '/spedizioni'
      fullPath: '/spedizioni'
      preLoaderRoute: typeof AppSpedizioniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ricettario': {
      id: '/_app/ricettario'
      path: '/ricettario'
      fullPath: '/ricettario'
      preLoaderRoute: typeof AppRicettarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/magazzino': {
      id: '/_app/magazzino'
      path: '/magazzino'
      fullPath: '/magazzino'
      preLoaderRoute: typeof AppMagazzinoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnostica': {
      id: '/_app/diagnostica'
      path: '/diagnostica'
      fullPath: '/diagnostica'
      preLoaderRoute: typeof AppDiagnosticaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anagrafica': {
      id: '/_app/anagrafica'
      path: '/anagrafica'
      fullPath: '/anagrafica'
      preLoaderRoute: typeof AppAnagraficaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnostica/': {
      id: '/_app/diagnostica/'
      path: '/'
      fullPath: '/diagnostica/'
      preLoaderRoute: typeof AppDiagnosticaIndexRouteImport
      parentRoute: typeof AppDiagnosticaRoute
    }
    '/_app/diagnostica/log': {
      id: '/_app/diagnostica/log'
      path: '/log'
      fullPath: '/diagnostica/log'
      preLoaderRoute: typeof AppDiagnosticaLogRouteImport
      parentRoute: typeof AppDiagnosticaRoute
    }
    '/_app/diagnostica/errori': {
      id: '/_app/diagnostica/errori'
      path: '/errori'
      fullPath: '/diagnostica/errori'
      preLoaderRoute: typeof AppDiagnosticaErroriRouteImport
      parentRoute: typeof AppDiagnosticaRoute
    }
    '/_app/diagnostica/codici-errori': {
      id: '/_app/diagnostica/codici-errori'
      path: '/codici-errori'
      fullPath: '/diagnostica/codici-errori'
      preLoaderRoute: typeof AppDiagnosticaCodiciErroriRouteImport
      parentRoute: typeof AppDiagnosticaRoute
    }
  }
}

interface AppDiagnosticaRouteChildren {
  AppDiagnosticaCodiciErroriRoute: typeof AppDiagnosticaCodiciErroriRoute
  AppDiagnosticaErroriRoute: typeof AppDiagnosticaErroriRoute
  AppDiagnosticaLogRoute: typeof AppDiagnosticaLogRoute
  AppDiagnosticaIndexRoute: typeof AppDiagnosticaIndexRoute
}

const AppDiagnosticaRouteChildren: AppDiagnosticaRouteChildren = {
  AppDiagnosticaCodiciErroriRoute: AppDiagnosticaCodiciErroriRoute,
  AppDiagnosticaErroriRoute: AppDiagnosticaErroriRoute,
  AppDiagnosticaLogRoute: AppDiagnosticaLogRoute,
  AppDiagnosticaIndexRoute: AppDiagnosticaIndexRoute,
}

const AppDiagnosticaRouteWithChildren = AppDiagnosticaRoute._addFileChildren(
  AppDiagnosticaRouteChildren,
)

interface AppRouteChildren {
  AppAnagraficaRoute: typeof AppAnagraficaRoute
  AppDiagnosticaRoute: typeof AppDiagnosticaRouteWithChildren
  AppMagazzinoRoute: typeof AppMagazzinoRoute
  AppRicettarioRoute: typeof AppRicettarioRoute
  AppSpedizioniRoute: typeof AppSpedizioniRoute
  AppStampeRoute: typeof AppStampeRoute
  AppStoricoRoute: typeof AppStoricoRoute
  AppVersamentoRoute: typeof AppVersamentoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnagraficaRoute: AppAnagraficaRoute,
  AppDiagnosticaRoute: AppDiagnosticaRouteWithChildren,
  AppMagazzinoRoute: AppMagazzinoRoute,
  AppRicettarioRoute: AppRicettarioRoute,
  AppSpedizioniRoute: AppSpedizioniRoute,
  AppStampeRoute: AppStampeRoute,
  AppStoricoRoute: AppStoricoRoute,
  AppVersamentoRoute: AppVersamentoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
