/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVersamentoRouteImport } from './routes/_app.versamento'
import { Route as AppStoricoRouteImport } from './routes/_app.storico'
import { Route as AppStampeRouteImport } from './routes/_app.stampe'
import { Route as AppSpedizioniRouteImport } from './routes/_app.spedizioni'
import { Route as AppAnagraficaRouteImport } from './routes/_app.anagrafica'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVersamentoRoute = AppVersamentoRouteImport.update({
  id: '/versamento',
  path: '/versamento',
  getParentRoute: () => AppRoute,
} as any)
const AppStoricoRoute = AppStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AppRoute,
} as any)
const AppStampeRoute = AppStampeRouteImport.update({
  id: '/stampe',
  path: '/stampe',
  getParentRoute: () => AppRoute,
} as any)
const AppSpedizioniRoute = AppSpedizioniRouteImport.update({
  id: '/spedizioni',
  path: '/spedizioni',
  getParentRoute: () => AppRoute,
} as any)
const AppAnagraficaRoute = AppAnagraficaRouteImport.update({
  id: '/anagrafica',
  path: '/anagrafica',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/anagrafica': typeof AppAnagraficaRoute
  '/spedizioni': typeof AppSpedizioniRoute
  '/stampe': typeof AppStampeRoute
  '/storico': typeof AppStoricoRoute
  '/versamento': typeof AppVersamentoRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/anagrafica': typeof AppAnagraficaRoute
  '/spedizioni': typeof AppSpedizioniRoute
  '/stampe': typeof AppStampeRoute
  '/storico': typeof AppStoricoRoute
  '/versamento': typeof AppVersamentoRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/anagrafica': typeof AppAnagraficaRoute
  '/_app/spedizioni': typeof AppSpedizioniRoute
  '/_app/stampe': typeof AppStampeRoute
  '/_app/storico': typeof AppStoricoRoute
  '/_app/versamento': typeof AppVersamentoRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/anagrafica'
    | '/spedizioni'
    | '/stampe'
    | '/storico'
    | '/versamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/anagrafica'
    | '/spedizioni'
    | '/stampe'
    | '/storico'
    | '/versamento'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/anagrafica'
    | '/_app/spedizioni'
    | '/_app/stampe'
    | '/_app/storico'
    | '/_app/versamento'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/versamento': {
      id: '/_app/versamento'
      path: '/versamento'
      fullPath: '/versamento'
      preLoaderRoute: typeof AppVersamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storico': {
      id: '/_app/storico'
      path: '/storico'
      fullPath: '/storico'
      preLoaderRoute: typeof AppStoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stampe': {
      id: '/_app/stampe'
      path: '/stampe'
      fullPath: '/stampe'
      preLoaderRoute: typeof AppStampeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spedizioni': {
      id: '/_app/spedizioni'
      path: '/spedizioni'
      fullPath: '/spedizioni'
      preLoaderRoute: typeof AppSpedizioniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anagrafica': {
      id: '/_app/anagrafica'
      path: '/anagrafica'
      fullPath: '/anagrafica'
      preLoaderRoute: typeof AppAnagraficaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnagraficaRoute: typeof AppAnagraficaRoute
  AppSpedizioniRoute: typeof AppSpedizioniRoute
  AppStampeRoute: typeof AppStampeRoute
  AppStoricoRoute: typeof AppStoricoRoute
  AppVersamentoRoute: typeof AppVersamentoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnagraficaRoute: AppAnagraficaRoute,
  AppSpedizioniRoute: AppSpedizioniRoute,
  AppStampeRoute: AppStampeRoute,
  AppStoricoRoute: AppStoricoRoute,
  AppVersamentoRoute: AppVersamentoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
